import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MindARThreeViewer from "@/components/MindARThreeViewer";
import { useState } from "react";
import MindARViewer from "@/components/MindARViewer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [startThreeAR, setStartThreeAR] = useState(false);
  const [startAFrameAR, setStartAFrameAR] = useState(false);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <button
          onClick={() => {
            setStartThreeAR(true);
          }}
        >
          ThreeARスタート！
        </button>
        <button
          onClick={() => {
            setStartAFrameAR(true);
          }}
        >
          AFrameARスタート！
        </button>
        {startThreeAR && <MindARThreeViewer />}
        {startAFrameAR && <MindARViewer />}
      </main>
    </>
  );
}
